#!/bin/bash
# website
#
#	Purpose:
#		
#	Description:
#		
#	History:
#		Fri Dec 15 13:21:48 CST 2018, Created by jimmyshiau
#
# Copyright (C) 2017 Potix Corporation. All Rights Reserved.
docker stop api-website
docker run --rm \
  --name api-website \
  -p 5000:80 \
  --volume="$PWD/dist:/home" \
  --volume="$PWD/tool/quire.conf:/etc/nginx/conf.d/default.conf:ro" \
  -d nginx

open http://localhost:5000/api-reference/